name: Docker-Pgadmin

services:
  pgadmin:
    image: dpage/pgadmin4:${PGADMIN_VERSION-latest}
    container_name: Docker-Pgadmin
    ports:
      - 8080:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - pgadmin_data:/data
    networks:
      - pgadmin
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}

networks:
  pgadmin:
    driver: bridge

volumes:
  pgadmin_data:
    driver: local