name: Docker-Portainer

services:
  portainer:
    image: portainer/portainer-ce:${PORTAINER_VERSION-latest}
    container_name: Docker-Portainer
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - portainer
    restart: unless-stopped

networks:
  portainer:
    driver: bridge

volumes:
  portainer_data:
    driver: local